version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: yassir_smtp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  api:
    build: ../
    command: npm run dev --workspace=apps/api
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/yassir_smtp
      REDIS_URL: redis://redis:6379
      MASTER_KEY: changeme-base64
      JWT_SECRET: devsecret
    depends_on:
      - postgres
      - redis
  worker:
    build: ../
    command: npm run dev --workspace=apps/worker
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/yassir_smtp
      REDIS_URL: redis://redis:6379
      MASTER_KEY: changeme-base64
      JWT_SECRET: devsecret
    depends_on:
      - postgres
      - redis
  web:
    build: ../
    command: npm run dev --workspace=apps/web
    environment:
      NEXT_PUBLIC_API_BASE: http://api:3001
    ports:
      - "3000:3000"
    depends_on:
      - api
volumes:
  pgdata:
