services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: yassir_smtp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: ../
    command: pnpm --filter @yassir/api dev
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/yassir_smtp
      REDIS_URL: redis://redis:6379
      MASTER_KEY: changeme-base64
      JWT_SECRET: devsecret
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3001:3001"
  worker:
    build: ../
    command: pnpm --filter @yassir/worker dev
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/yassir_smtp
      REDIS_URL: redis://redis:6379
      MASTER_KEY: changeme-base64
      JWT_SECRET: devsecret
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  web:
    build: ../
    command: pnpm --filter @yassir/web dev
    environment:
      NEXT_PUBLIC_API_BASE: http://api:3001
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started
volumes:
  pgdata:
